from functions1 import ounces_to_grams, conversion, solve, filter_prime, print_permutations, reverse, has_33, spy_game, volume, unique, is_palindrome, histogram, guess_the_number
print(ounces_to_grams(350))
print(conversion(230))
print(solve(35, 94))
print(filter_prime([1, 2, 3, 4, 5, 6, 7, 8, 9]))
print(print_permutations("you"))
print(reverse("We are ready"))
print(has_33([1, 3, 3]))
print(spy_game([1, 0, 0, 7, 5]))
print(volume(5))
print(unique([1, 2, 3, 4, 5, 5, 5]))
print(is_palindrome("palindrome"))
print(histogram([1, 2, 3]))
print(guess_the_number())